<a href="https://colab.research.google.com/github/Lstemm/DSC-502/blob/main/DSC_502_HW1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
filename = '/content/drive/MyDrive/Copy of olympic_medals.csv'
import pandas as pd
df = pd.read_csv(filename)

In [3]:
# a
df.shape

(2394, 8)

The dataframe has 2394 roes and 8 colmns.

In [5]:
# b
df.dtypes

Gender         object
Event          object
Location       object
Year            int64
Medal          object
Name           object
Nationality    object
Result         object
dtype: object

The "Year" column is of type "int64", and all other columns are of type "object".

In [9]:
# c
len(df['Location'].unique())

23

Matches were held at 23 unique cities.

In [12]:
# d
df_usa = df[(df["Nationality"] == "USA")]
len(df_usa)

638

The USA Team won 638 medals total

In [15]:
# e
df.groupby(by='Nationality')['Medal'].count()

Nationality
ALG      9
ARG      4
AUS     57
AUT      4
BAH     12
      ... 
URS    131
USA    638
VEN      2
YUG      1
ZAM      1
Name: Medal, Length: 97, dtype: int64